### PR TITLE
Switch to cht-gateway

### PR DESCRIPTION
**Pull request by dianabarsan**
medic/cht-core#6586

### CODE REVIEW

**Comment by dianabarsan** [comment]
Before: 
image
image
image

After:
image
image

**Comment by dianabarsan** [comment]
Please have a look, @latin-panda . Thanks for your time!

**Review by mrsarm — COMMENTED** [review]
Hey @dianabarsan , aame observations than https://github.com/medic/medic-android/pull/179#pullrequestreview-669140945.

**Comment by dianabarsan** [comment]
hey @latin-panda . Please hold off the review, I'm going to also change the project name to `cht-gateway` as per https://github.com/medic/cht-core/issues/6586#issuecomment-849161332. Thanks!

**Comment by dianabarsan** [comment]
hey, @latin-panda , I think I got everything! Please review when convenient! thanks!

**Review by latin-panda — APPROVED** [review]
Nice job! I tested the APK and the code and looks good :)

**Review by mrsarm — APPROVED** [review]
LGTM :+1:

**Pull request merged**
